server:
  port: 8001
spring:
  application:
    name: dept-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/microservicecloud_db_01?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-provider-8001
    prefer-ip-address: true
info:
  msg.port: ${server.port}
  msg.message: dept-provider-message
mybatis:
  type-aliases-package: com.ultra.cloud.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml